-- 消防设施巡检维保平台初始化结构。
-- 数据由后端启动时通过 seed_if_empty 写入；此文件仅保证结构先行存在。

CREATE TABLE IF NOT EXISTS sys_user (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) UNIQUE NOT NULL,
  password_hash VARCHAR(128) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  role VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS building (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  campus VARCHAR(128) NOT NULL,
  floor_count INTEGER NOT NULL,
  fire_grade VARCHAR(32) NOT NULL,
  manager_id INTEGER,
  address_code VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS fire_device (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  building_id INTEGER NOT NULL,
  device_code VARCHAR(64) UNIQUE NOT NULL,
  device_type VARCHAR(32) NOT NULL,
  floor VARCHAR(16) NOT NULL,
  location_desc VARCHAR(255) NOT NULL,
  install_date DATE,
  status VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
  next_maintenance_at DATE
);

CREATE TABLE IF NOT EXISTS inspection_task (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  building_id INTEGER NOT NULL,
  inspector_id INTEGER,
  plan_date DATE NOT NULL,
  task_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PLANNED',
  checklist_version VARCHAR(32) NOT NULL DEFAULT 'v1.0',
  finished_at TIMESTAMP,
  created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inspection_result (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id INTEGER NOT NULL,
  device_id INTEGER NOT NULL,
  item_code VARCHAR(64) NOT NULL,
  result_status VARCHAR(32) NOT NULL,
  measured_value VARCHAR(255) DEFAULT '',
  photo_url VARCHAR(255) DEFAULT '',
  note VARCHAR(255) DEFAULT '',
  updated_at TIMESTAMP,
  CONSTRAINT uq_result_task_device_item UNIQUE (task_id, device_id, item_code)
);

CREATE TABLE IF NOT EXISTS hazard_ticket (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  result_id INTEGER UNIQUE NOT NULL,
  severity VARCHAR(32) NOT NULL,
  owner_id INTEGER NOT NULL,
  deadline DATE NOT NULL,
  rectify_status VARCHAR(32) NOT NULL DEFAULT 'ASSIGNED',
  rectify_note VARCHAR(1000) DEFAULT '',
  closed_at TIMESTAMP,
  created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor VARCHAR(64) NOT NULL,
  action VARCHAR(255) NOT NULL,
  target_type VARCHAR(64) NOT NULL,
  target_id VARCHAR(64) NOT NULL,
  created_at TIMESTAMP
);
