ERROR_CODES = {
    "AUTH_REQUIRED": "AUTH_REQUIRED",
    "LOGIN_FAILED": "LOGIN_FAILED",
    "RBAC_DENIED": "RBAC_DENIED",
    "VALIDATION_FAILED": "VALIDATION_FAILED",
    "NOT_FOUND": "NOT_FOUND",
    "STATE_CONFLICT": "STATE_CONFLICT",
    "RATE_LIMITED": "RATE_LIMITED",
    "INTERNAL_ERROR": "INTERNAL_ERROR",
}
